### ISSUE TITLE
JSON validation error

### ISSUE THREAD

**Issue by rewilson** [singer-io/tap-xero#20]
This happens on 0.1.16 as of this morning.
```
Expecting property name enclosed in double quotes: line 157 column 5 (char 2540)
```

Maybe a trailling comma in [bank_transactions.json](https://github.com/singer-io/tap-xero/blob/ebd6eb6c7dce78dbbbfbbe8b0ebd666b72fcc3bb/tap_xero/schemas/bank_transactions.json#L156) (near the `ExternalLinkProviderName` property)?

 Logs below. 
```
2018-01-25 23:15:03,662Z   main - INFO Running tap-xero version 0.1.16 and target-stitch version 1.7.0
2018-01-25 23:15:03,821Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-xero --config /tmp/tap_discover_config.json --discover
2018-01-25 23:15:04,468Z    tap - INFO Attempting refresh with config credentials.
2018-01-25 23:15:04,468Z    tap - INFO Refreshing credentials
2018-01-25 23:15:05,006Z    tap - INFO Config credentials failed.  Attempting refresh with s3 credentials.
2018-01-25 23:15:05,006Z    tap - INFO Refreshing credentials
2018-01-25 23:15:05,383Z    tap - CRITICAL Expecting property name enclosed in double quotes: line 157 column 5 (char 2540)
2018-01-25 23:15:05,386Z    tap - Traceback (most recent call last):
2018-01-25 23:15:05,386Z    tap -   File "tap-env/bin/tap-xero", line 11, in <module>
2018-01-25 23:15:05,387Z    tap -     sys.exit(main())
2018-01-25 23:15:05,387Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_xero/__init__.py", line 142, in main
2018-01-25 23:15:05,387Z    tap -     raise exc
2018-01-25 23:15:05,387Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_xero/__init__.py", line 139, in main
2018-01-25 23:15:05,387Z    tap -     main_impl()
2018-01-25 23:15:05,387Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_xero/__init__.py", line 130, in main_impl
2018-01-25 23:15:05,387Z    tap -     discover(args.config).dump()
2018-01-25 23:15:05,388Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_xero/__init__.py", line 88, in discover
2018-01-25 23:15:05,388Z    tap -     schema = Schema.from_dict(load_schema(stream.tap_stream_id),
2018-01-25 23:15:05,388Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_xero/__init__.py", line 39, in load_schema
2018-01-25 23:15:05,388Z    tap -     schema = utils.load_json(get_abs_path(path))
2018-01-25 23:15:05,388Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 65, in load_json
2018-01-25 23:15:05,389Z    tap -     return json.load(fil)
2018-01-25 23:15:05,389Z    tap -   File "/usr/lib/python3.5/json/__init__.py", line 268, in load
2018-01-25 23:15:05,389Z    tap -     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
2018-01-25 23:15:05,389Z    tap -   File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
2018-01-25 23:15:05,389Z    tap -     return _default_decoder.decode(s)
2018-01-25 23:15:05,389Z    tap -   File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
2018-01-25 23:15:05,390Z    tap -     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2018-01-25 23:15:05,390Z    tap -   File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
2018-01-25 23:15:05,390Z    tap -     obj, end = self.scan_once(s, idx)
2018-01-25 23:15:05,390Z    tap - json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 157 column 5 (char 2540)
2018-01-25 23:15:05,506Z   main - INFO Tap exited abnormally with status 1
2018-01-25 23:15:05,507Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "Expecting property name enclosed in double quotes: line 157 column 5 (char 2540)".
```

**Comment by KAllan357** [comment]
Thanks for catching this. Will publish a fix momentarily.

**Comment by rewilson** [comment]
Great, thanks!

**Comment by KAllan357** [comment]
Be on the lookout for a run on version `0.1.17`. Please feel free to close this if its resolved.

**Comment by rewilson** [comment]
Thanks @KAllan357  - that fixed the issues. I found one more schema validation issue and submitted a PR for it (#21)
