### ISSUE TITLE
Authentication with a private application unclear

### ISSUE THREAD

**Issue by sminnee** [singer-io/tap-xero#41]
I'm trying to use this to access our Xero data. I've set up a private application to do this but I get this error

It seems as though it's not designed to be used with private applications? Setting up a Public App for my one-off integration seems overkill.

Is there any documentation for this tap?

```
CRITICAL 'oauth_token'
Traceback (most recent call last):
  File "/usr/local/bin/tap-xero", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/tap_xero/__init__.py", line 142, in main
    raise exc
  File "/usr/local/lib/python3.6/site-packages/tap_xero/__init__.py", line 139, in main
    main_impl()
  File "/usr/local/lib/python3.6/site-packages/tap_xero/__init__.py", line 135, in main_impl
    sync(Context(args.config, args.state, catalog))
  File "/usr/local/lib/python3.6/site-packages/tap_xero/context.py", line 11, in __init__
    self.client = XeroClient(config)
  File "/usr/local/lib/python3.6/site-packages/tap_xero/http.py", line 35, in __init__
    self.oauth = build_oauth(config)
  File "/usr/local/lib/python3.6/site-packages/tap_xero/credentials.py", line 54, in build_oauth
    resource_owner_key=config["oauth_token"],
KeyError: 'oauth_token'
```

**Comment by sminnee** [comment]
Yeah I've found an alternative solution for my needs with Stitch and so I'm unlikely to supply a PR for this.
